#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os, os.path
from bs4 import BeautifulSoup
import configparser


bash_categories = [name for name in os.listdir("./bash/") if os.path.isdir("./bash/" + name)]
config = configparser.ConfigParser()

f = open('bash/index.html', 'w')

html_template_pre = """<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SysAdmin's ToolBox</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.6" />
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.4/umd/popper.min.js"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6710021794174728" crossorigin="anonymous"></script>
    <script src="/js/common.js"></script>
  </head>
  <body>
    <div class="container-fluid"></br>
      <div class="row">
        <div class="col-sm"><h2>Categories of BASH Commands</h2></div>
      </div></br>
"""

html_template_divlist = """      <div id="toolList" class="list-group">
        <input id="inpSearch" onkeyup="searchFunction()" class="form-control" type="text" placeholder="Search">
"""

html_template_link_list = ""

for category in bash_categories:
  config.read('bash/' + category + '/' + category + '.cfg')
  html_template_link_list = html_template_link_list + '        <a href="/bash/' + category + '/index.html" class="list-group-item list-group-item-action"><h5>' \
                            + config['Main']['title'] + '</h5></a>\n'

html_template_divlist = html_template_divlist + html_template_link_list + '      </div></br>\n'

html_template_post = """    </div>
    <a href="/" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-home"></span> <h5>Tools Home</h5></a>
  </body>
</html>
"""

html_template = html_template_pre + html_template_divlist + html_template_post

f.write(html_template)
f.close()

