#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os, os.path
from bs4 import BeautifulSoup

bash_categories = [name for name in os.listdir("./bash/") if os.path.isdir("./bash/" + name)]
main_html_pages = [name for name in os.listdir(".") if os.path.isfile(name) and name.endswith(".html") and name != "index.html" and name != "main_index.html"]

f = open('index.html', 'w')

html_template_pre = """<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SysAdmin's ToolBox</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.6" />
    <meta name="description" content="This app offers helpful tools that a Linux sysadmin might need. It is also a bash command generator." />
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.4/umd/popper.min.js"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6710021794174728" crossorigin="anonymous"></script>
    <script src="/js/common.js"></script>
  </head>
  <body>
    <div class="container-fluid"></br>
      <div class="row">
        <div class="col-sm">This app offers helpful tools that a Linux sysadmin might need. It is also a bash command generator.</div>
      </div></br>
      <div class="row">
        <div class="col-sm"><h2>List of Tools</h2></div>
      </div></br>
"""

html_template_divlist = """      <div id="toolList" class="list-group">
        <input id="inpSearch" onkeyup="searchFunction()" class="form-control" type="text" placeholder="Search">
"""

html_template_divlist = html_template_divlist + '        <a href="/bash/index.html" class="list-group-item list-group-item-action">' \
                                              + '<h5>Generate BASH Commands &nbsp;<span class="badge badge-info">' \
                                              + str(len(bash_categories)) + '</span></h5></a>\n'

html_template_link_list = ""

for page in main_html_pages:
  print(page)
  with open(page) as fp:
    soup = BeautifulSoup(fp, 'html.parser')
  html_template_link_list = html_template_link_list + '        <a href="/' + page + '" class="list-group-item list-group-item-action"><h5>' \
                            + soup.title.string + '</h5></a>\n'

html_template_divlist = html_template_divlist + html_template_link_list + '      </div>\n'

html_template_post = """    </div>
  </body>
</html>
"""

html_template = html_template_pre + html_template_divlist + html_template_post

f.write(html_template)
f.close()

